### ISSUE TITLE
Release Checklist 0.5.0

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#527]
- [x] tag and build 0.5.0 (https://github.com/sigstore/sigstore-java/releases/tag/v0.5.0)
- [x] release to maven central (https://repo1.maven.org/maven2/dev/sigstore/sigstore-java/0.5.0/)
- [x]  release gradle plugin to gradle plugin portal
- [x] update project version and README

FYI: @patflynn @vlsi

**Comment by patflynn** [comment]
👍

**Comment by loosebazooka** [comment]
@vlsi any chance you could do a gradle plugin release?
