### ISSUE TITLE
Release 0.6.0 checklist

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#566]
- [x] tag and build 0.6.0 (https://github.com/sigstore/sigstore-java/releases/tag/v0.6.0)
- [x] release to maven central (https://repo1.maven.org/maven2/dev/sigstore/sigstore-java/0.6.0/)
- [ ]  release gradle plugin to gradle plugin portal
- [ ] update project version and README

FYI: @patflynn @vlsi

**Comment by vlsi** [comment]
WDYT of releasing 0.6.0 as 1.0.0?

**Comment by loosebazooka** [comment]
I think we've made a few changes since?

**Comment by loosebazooka** [comment]
Id like to do a 0.7.0 with the new release mechanism first? And maybe we have. `.sigstore.json` as the default on the bundle output?

**Comment by vlsi** [comment]
>Id like to do a 0.7.0 with the new release mechanism first?

That is not a user-visible change, so it can go within any version.

>And maybe we have. .sigstore.json as the default on the bundle output?

I missed the change.
For reference, here are the traces:

* https://github.com/sigstore/sig-clients/issues/8#issuecomment-1663046593
* https://docs.google.com/document/d/1kbhK2qyPPk8SLavHzYSDM8-Ueul9_oxIMVFuWMWKz0E/edit#heading=h.frw4lfrx4pv0

>If clients serialize the bundle to a file, the file SHOULD have the extension `.sigstore.json`. To write multiple bundles in one file, clients SHOULD use the [JSON Lines](https://jsonlines.org/) format (format each bundle without newlines, and write one bundle per line) and the extension `.sigstore.jsonl`

@hboutemy , do you know if Sonatype OSSRH is prepared to handle `.sigstore.json` (and `.sigstore.jsonl`) without `.sigstore.json.asc`?

Frankly speaking, I am not sure we need `.sigstore.jsonl` for Java-like use cases yet, however, the spec suggests two formats.

**Comment by loosebazooka** [comment]
Yeah for .sigstore.jdon I think Joel is working on it

**Comment by loosebazooka** [comment]
this is superseded by 0.7.0 release
