### ISSUE TITLE
Release 0.7.0 checklist

### ISSUE THREAD

**Issue by loosebazooka** [sigstore/sigstore-java#623]
- [x] tag 0.7.0
- [x] build and release to maven central (https://repo1.maven.org/maven2/dev/sigstore/sigstore-java/0.7.0/)
- [x] build and release gradle plugin to gradle plugin portal (https://plugins.gradle.org/plugin/dev.sigstore.sign)
- [x] update project version and README (#624)

FYI: @patflynn @vlsi
